datacollect/views/admin.py
# coding: utf-8


from flask import Blueprint, render_template, request, jsonify, url_for
from werkzeug.security import generate_password_hash
from werkzeug.utils import redirect

from datacollect import get_db
from datacollect.common import Result
from datacollect.dao import select
from datacollect.views.auth import login_required

bp = Blueprint('admin', __name__, url_prefix='/admin')


@bp.route("/users")
def users():
    return render_template("admin/users.html")


@bp.route("/query_user", methods=["POST"])
def query_user():
    param = request.json
    total, rows = select(
        db=get_db(),
        select_fields=[
            "id", "username", "role"
        ],
        table_name="user",
        param=param
    )
    data = {"total": total, "rows": rows}
    return jsonify(data)


@bp.route("/save_user", methods=["POST"])
def save_user():
    param = request.json
    role = param.get("role") or "user"
    username = param.get("username")
    user_id = param.get("user_id")
    db = get_db()
    result = Result()

    if not username:
        result.message = '请输入用户名'
    else:
        if not user_id:
            sql = 'SELECT id FROM user WHERE username = ?'
            if db.execute(sql, (username,)).fetchone() is not None:
                result.message = '用户名 {0} 已经存在'.format(username)

    if result:
        if not user_id:
            db.execute(
                'INSERT INTO user (username, role, password) VALUES (?, ?, ?)',
                (username, role, generate_password_hash("888888"))
            )
        else:
            db.execute(
                'update user set username=?, role=? where id=?',
                (username, role, user_id)
            )
        db.commit()

    return jsonify(result.to_json())


@bp.route('/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    users.delete_by_id(get_db(), id)
    return "ok"


@bp.route("/change_password", methods=["POST"])
def change_password():
    """修改密码"""
    param = request.json
    user_id = param.get("user_id")
    password = param.get("password")
    db = get_db()
    result = Result()

    if not password:
        result.message = '请输入新密码'
    else:
        sql = 'update user set password=? where id=?'
        db.execute(sql, (generate_password_hash(password), user_id))
        db.commit()
    return jsonify(result.to_json())

web/templates/base.html
<!doctype html>
<html lang="zh_CN">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-4.1.3.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-table.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/layout.main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.responsive.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.quickfix.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/common.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/open-iconic-bootstrap.css') }}">
    <title>{% block title %}污染源普查{% endblock %}</title>
    {% block header %}{% endblock %}
  </head>
  <body>
    <div class="modal" id="confirm_modal">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title">确认</h5>
                  <button type="button" class="close" data-dismiss="modal">
                      <span aria-hidden="true">&times;</span>
                      <span class="sr-only">Close</span>
                  </button>
              </div>
              <div class="modal-body">
                <input type="hidden" id="confirm_dialog_value">
                <p id="confirm_message">确认删除吗？</p>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                  <button id="btn_confirm_ok" type="button" class="btn btn-primary">确定</button>
              </div>
          </div>
      </div>
    </div>
    {% block modal %}{% endblock %}
    <div id="wrap">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <img style="margin-right: 10px;" src="{{ url_for('static', filename='img/login.png') }}" alt="" width="60" height="60">
        <a class="navbar-brand" href="#">污染源普查系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown show">
              <a class="nav-link dropdown-toggle" href="https://example.com"
                 id="dropdown03" data-toggle="dropdown" aria-haspopup="true"
                 aria-expanded="false">调查表类型</a>
              <div class="dropdown-menu" aria-labelledby="dropdown03">
                {% for survey_type in g.survey_types %}
                <a class="dropdown-item" href="/{{survey_type['index_page']}}">{{ survey_type['fullname']}}</a>
                {% endfor %}
              </div>
            </li>
            {% if g.user.role=='manager' %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.users') }}">用户管理</a>
            </li>
            {% endif %}
          </ul>
          <form class="form-inline mt-2 mt-md-0" action="/auth/logout">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">退出登录({{g.user.username}})</button>
          </form>
        </div>
      </nav>

      <!-- Begin page content -->
      <main id="content" role="main" class="container">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </main>
    </div>

    <div id="footer">
      <div class="container">
        <p>Your Company &copy; All Rights Reserved.</p>
        {% block footer %}{% endblock %}
      </div>
    </div>
    <script>
      var is_manager = false;
      {% if g.user['role'] == 'manager' %}
      is_manager = true;
      {% endif %}
    </script>
    <script src="{{ url_for('static', filename='js/jquery-3.3.1.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper-1.14.3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap-4.1.3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap-table.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap-table-zh-CN.js') }}"></script>
    {% block script %}{% endblock %}
  </body>
</html>